# DATA PREPARATION

In [1]:
# INITIATION: PYTHON AND DISPLAY

# Import libraries
import pandas as pd #
import numpy as np

# For better visibility
from IPython.display import display, HTML

# Apply a no-wrap style to prevent text wrapping
display(HTML("""
<style>
.dataframe td { white-space: nowrap; }
</style>
"""))

# Set the option to display all columns
pd.set_option('display.max_columns', None)

# Set the option to display all rows
pd.set_option('display.max_rows', None)

# Set the float format to use a space as a thousands separator and a comma as a decimal separator
pd.set_option('display.float_format', lambda x: f'{x:,.2f}'.replace(',', ' ').replace('.', ','))

In [2]:
# FILE LOAD and INTEGRATION

# Read the Excel file and specify that 'PKD' should be read as a string to preserve leading zeros
df = pd.read_excel('2000 Analysis Python.xlsx', decimal=',', dtype={'PKD': str})

pkd = pd.read_excel('2000 PKD.xlsx')  # Load the pkd data

# Convert 'PKD' to string and extract the first two characters (keeping leading zeros)
df['PKD_2'] = df['PKD'].astype(str).str.zfill(2).str[:2]

# Convert the 'PKD_2' column in pkd to a string to match the type of 'PKD'
pkd['PKD_2'] = pkd['PKD_2'].astype(str).str.zfill(2)

# Perform the merge using 'PKD' and 'Number'
df = pd.merge(
    df,
    pkd,
    left_on='PKD_2',
    right_on='PKD_2',
    how='left'
)

cols = df.columns.tolist()  # Get a list of all column names
cols.insert(25, cols.pop(cols.index('PKD_2'))) # Remove 'PKD_2' and insert it at index 25
df = df[cols]  # Reassign the DataFrame with the new column order

df.columns = df.columns.astype(str)

In [3]:
# FILE INSPECTION

# Print the number of rows and columns
print(f"Number of rows and columns: {df.shape}")

print("Number of companies = ", df[df['Year']==2023].shape[0])

# Display the first 5 rows of the DataFrame
display(df.head())

# Print the last 5 rows of the DataFrame
display(df.tail())

Number of rows and columns: (10000, 30)
Number of companies =  2000

,2023,2022,2021,2020,2019,Name,NIP,PKD,PKD Opis,Sector,Owner Type,Year,Sales,Gross Profit,Operating Profit,Net Profit,Depreciation,Export Sales,Employment,Staff costs,BS,Fixed Assets,Current Assets,Equity,Liabilities,PKD_2,PKD_1,PKD_1 Description,PKD_2 Description,Digital intensity
0,1,"1,00","1,00","1,00","1,00","Orlen SA GK, Płock",7740001454,1920,Wytwarzanie i przetwarzanie produktów rafinacj...,Oil,412,2023,372767000,"28 056 000,00",30314000,20727000,142000,102589000,66554,"11 175 000,00",264178000,170795000,93383000,153180000,"110 998 000,00",19,C,Manufacturing,MANUFACTURE AND PROCESSING OF COKE AND REFINED...,Medium-high
1,2,"2,00","3,00","2,00","2,00","Jeronimo Martins Polska SA, Kostrzyn",7791011327,4719,Pozostała sprzedaż detaliczna prowadzona w nie...,Retail,500,2023,98022928,"4 882 170,96","5 121 150,49","4 127 757,73","1 311 227,50",0,79292,"5 954 379,19","26 597 526,53","11 978 435,65","14 619 090,88",5299163,"21 298 363,10",47,G,Wholesale and Retail Trade; Repair of Motor Ve...,"RETAIL TRADE, EXCEPT OF MOTOR VEHICLES",Medium-high
2,3,"3,00","4,00","3,00","4,00","PGE Polska Grupa Energetyczna GK SA, Lublin",5260250541,7010,Działalność firm centralnych (head offices) i ...,Energy,145,2023,95964000,"-3 431 000,00",-4055000,-4902000,13455000,25000,42552,"6 287 000,00",113443000,78340000,35103000,47855000,"65 588 000,00",70,M,"Professional, Scientific and Technical Activities",ACTIVITIES OF HEAD OFFICES; MANAGEMENT CONSULT...,High
3,4,"5,00","11,00","17,00","30,00","Totalizator Sportowy sp. z o.o. GK, Warszawa",5250010982,9200,Działalność związana z grami losowymi i zakład...,Services,100,2023,52269058,"385 142,00",453419,362474,189397,0,5894,"786 162,00",2893324,1099674,1793650,1669328,"1 223 996,00",92,R,"Arts, Entertainment and Recreation",GAMBLING AND BETTING ACTIVITIES,Medium-high
4,5,"11,00","14,00","13,00","15,00","Enea SA GK, Poznań",7770020640,3514,Handel energią elektryczną,Energy,145,2023,48183419,"955 679,00",-508049,-442623,1651920,0,17853,"3 092 964,00",39110745,21636978,17473767,15439599,"23 671 146,00",35,D,"Electricity, Gas, Steam, Hot Water and Air Con...","ELECTRICITY, GAS, STEAM, HOT WATER AND AIR CON...",Low

,2023,2022,2021,2020,2019,Name,NIP,PKD,PKD Opis,Sector,Owner Type,Year,Sales,Gross Profit,Operating Profit,Net Profit,Depreciation,Export Sales,Employment,Staff costs,BS,Fixed Assets,Current Assets,Equity,Liabilities,PKD_2,PKD_1,PKD_1 Description,PKD_2 Description,Digital intensity
9995,1996,"1 542,00",NaN,NaN,NaN,"Qemetica Silicates SA, Iłowa",9240004491,2013,Production pozostałych podstawowych chemikalió...,Chemicals,400,2019,"237 477,58","22 831,76","20 004,98","15 803,04",16515,100221,322,"23 226,00","165 617,79","79 478,63","86 139,17","116 358,33","49 259,47",20,C,Manufacturing,MANUFACTURE OF CHEMICALS AND CHEMICAL PRODUCTS,Medium-low
9996,1997,NaN,NaN,NaN,NaN,"Tuplex TD sp. z o.o., Warszawa",5242435833,4676,Sprzedaż hurtowa pozostałych półproduktów,Wholesale,400,2019,0,"0,00",0,0,0,0,0,"0,00",0,0,0,0,"0,00",46,G,Wholesale and Retail Trade; Repair of Motor Ve...,"WHOLESALE TRADE, EXCEPT OF MOTOR VEHICLES",Medium-high
9997,1998,NaN,NaN,"788,00",NaN,"TZF Polfa SA, Warszawa",5250000564,2120,Production leków i pozostałych wyrobów farmace...,Healthcare and pharma,400,2019,"250 218,63","46 581,07","43 408,01","33 852,07","18 386,18",0,1082,"83 287,77","580 343,79","239 888,88","340 454,91","264 380,78","315 963,01",21,C,Manufacturing,MANUFACTURE OF BASIC PHARMACEUTICAL PRODUCTS A...,Medium-low
9998,1999,NaN,NaN,NaN,NaN,"Angelini Pharma Polska sp. z o.o., Warszawa",5260204222,4646,Sprzedaż hurtowa wyrobów farmaceutycznych i me...,Healthcare and pharma,500,2019,"241 910,51","15 184,60","15 332,07","11 292,22","3 111,34",671,218,"34 841,54","143 346,67","5 208,00","138 138,67","67 212,81","76 133,86",46,G,Wholesale and Retail Trade; Repair of Motor Ve...,"WHOLESALE TRADE, EXCEPT OF MOTOR VEHICLES",Medium-high
9999,2000,NaN,"1 855,00","1 939,00","1 863,00","Yes Biżuteria SA GK, Poznań",7780171607,4777,"Sprzedaż detaliczna zegarków, zegarów i biżute...",Production,400,2019,"310 627,45","42 356,08","38 857,33","30 760,02","7 316,27",1487,274,"26 996,90","237 529,12","31 685,71","205 843,41","194 444,25","43 084,88",47,G,Wholesale and Retail Trade; Repair of Motor Ve...,"RETAIL TRADE, EXCEPT OF MOTOR VEHICLES",Medium-high

In [4]:
# DATA CLEAN-UP

# Step 1: Identify duplicates based on 'Name' and 'Year' columns
duplicates = df[df.duplicated(subset=['Name', 'Year'], keep=False)]

# Step 2: Display the duplicates for inspection
print("Duplicate rows based on 'Name' and 'Year':")
print(duplicates)

Duplicate rows based on 'Name' and 'Year':
Empty DataFrame
Columns: [2023, 2022, 2021, 2020, 2019, Name, NIP, PKD, PKD Opis, Sector, Owner Type, Year, Sales, Gross Profit, Operating Profit, Net Profit, Depreciation, Export Sales, Employment, Staff costs, BS, Fixed Assets, Current Assets, Equity, Liabilities, PKD_2, PKD_1, PKD_1 Description, PKD_2 Description, Digital intensity]
Index: []

In [5]:
#DATA TYPES ASSIGNMENT

# Step 1: Changing data types for analysis
dtype_changes = {
    
    'PKD': 'category',
    'PKD_2': 'category',
    'PKD_1': 'category',
    'Sector': 'category',
    'Owner Type': 'category',
    'Year': 'category',
    'Sales': 'float',
    'Gross Profit': 'float',
    'Operating Profit': 'float',
    'Net Profit': 'float',
    'Depreciation': 'float',
    'Export Sales': 'float',
    'Employment': 'float',
    'Staff costs': 'float',
    'BS': 'float',
    'Operating Profit': 'float',
    'Fixed Assets': 'float',
    'Current Assets': 'float',
    'Equity': 'float',
    'Liabilities': 'float',
    'Digital intensity': 'category' 
    
    
    }
# Step 2: Check each column individually to identify possible issues

for col, dtype in dtype_changes.items():
    try:
        if dtype in ['float', 'int']:  # Check if the target type is numeric
            df[col] = pd.to_numeric(df[col], errors='coerce')  # Use pd.to_numeric for numeric conversion
        df[col] = df[col].astype(dtype)  # Convert to the target dtype
        print(f"Successfully converted {col} to {dtype}")
    except ValueError as e:
        print(f"Error converting {col} to {dtype}: {e}")

Successfully converted PKD to category
Successfully converted PKD_2 to category
Successfully converted PKD_1 to category
Successfully converted Sector to category
Successfully converted Owner Type to category
Successfully converted Year to category
Successfully converted Sales to float
Successfully converted Gross Profit to float
Successfully converted Operating Profit to float
Successfully converted Net Profit to float
Successfully converted Depreciation to float
Successfully converted Export Sales to float
Successfully converted Employment to float
Successfully converted Staff costs to float
Successfully converted BS to float
Successfully converted Fixed Assets to float
Successfully converted Current Assets to float
Successfully converted Equity to float
Successfully converted Liabilities to float
Successfully converted Digital intensity to category

In [6]:
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   2023               10000 non-null  int64
 1   2022               8485 non-null   float64
 2   2021               7920 non-null   float64
 3   2020               7850 non-null   float64
 4   2019               7675 non-null   float64
 5   Name               10000 non-null  object
 6   NIP                10000 non-null  int64
 7   PKD                10000 non-null  category
 8   PKD Opis           10000 non-null  object
 9   Sector             10000 non-null  category
 10  Owner Type         10000 non-null  category
 11  Year               10000 non-null  category
 12  Sales              9992 non-null   float64
 13  Gross Profit       9943 non-null   float64
 14  Operating Profit   9940 non-null   float64
 15  Net Profit         9947 non-null   float64
 16  Depreciation       9922 non-null   float64
 17  Export Sales       9881 non-null   float64
 18  Employment         9873 non-null   float64
 19  Staff costs        9900 non-null   float64
 20  BS                 9939 non-null   float64
 21  Fixed Assets       9934 non-null   float64
 22  Current Assets     9934 non-null   float64
 23  Equity             9938 non-null   float64
 24  Liabilities        9939 non-null   float64
 25  PKD_2              10000 non-null  category
 26  PKD_1              10000 non-null  category
 27  PKD_1 Description  10000 non-null  object
 28  PKD_2 Description  10000 non-null  object
 29  Digital intensity  10000 non-null  category
dtypes: category(7), float64(17), int64(2), object(4)
memory usage: 1.8+ MB

None

# ANALYSIS  SET-UP

In [7]:
# SET THE TECHNICAL FILTERS

# Step 1: Identify companies with missing or zero Sales or Employment in 2019 or 2023
names_to_remove = df[
    (df['Year'].isin([2019, 2023])) & 
    (
        (df['Sales'] == 0) | pd.isnull(df['Sales']) |
        (df['Employment'] == 0) | pd.isnull(df['Employment'])
    )
]['Name'].unique()

# Step 2: Filter them out
df_filter = df[~df['Name'].isin(names_to_remove)]

# Step 3: Summary
print(f"Number of companies removed due to missing Sales or Employment in 2019 or 2023: {len(names_to_remove)}")

count_df = df[
    (df['Year'] == 2023)
].shape[0]
print("Number of companies in 2023 before filtering = ", count_df)

count_df_filter = df_filter[df_filter['Year'] == 2023].shape[0]
print("Number of companies in 2023 after filtering = ", count_df_filter)

Number of companies removed due to missing Sales or Employment in 2019 or 2023: 113
Number of companies in 2023 before filtering =  2000
Number of companies in 2023 after filtering =  1887

In [8]:
#Lista firm usuniętych z analizy
df_print = df[df['Name'].isin(names_to_remove)]

display(df_print.pivot(index='Name', columns='Year', values='Employment'))

Year,2019,2020,2021,2022,2023
Name,,,,,
"AUTO-PARK sp. z o.o. sp.k., Białystok",NaN,NaN,NaN,"235,00","198,00"
"Accenture sp. z o.o. GK, Warszawa","0,00","0,00","7 809,00","7 809,00","8 261,00"
"Agro Kontrakt sp. z o.o., Olsztyn","0,00","0,00","1,00","8,00","9,00"
"Aramco Fuels Poland sp. z o.o., Gdańsk","0,00","0,00","0,00","207,00","239,00"
"Auto Partner Holding sp. z o.o., Kowale","0,00","0,00","0,00","250,00","252,00"
"B8 sp. z o.o. Baltic sp.k.a., Gdańsk","0,00","0,00","0,00","0,00","0,00"
"Bausch & Lomb Poland sp. z o.o., Warszawa","0,00","0,00","0,00","296,00","299,00"
"Baywa R.E. Solar Systems sp. z o.o., Zabierzów","0,00","0,00","34,00","48,00","75,00"
"Castrol CEE sp. z o.o., Warszawa","0,00","0,00","82,00","42,00","40,00"
"Coral Travel Poland sp. z o.o., Warszawa","0,00","0,00","307,00","331,00","392,00"
"DNP sp. z o.o., Wyrzysk",NaN,"451,00","557,00","730,00","828,00"
"Daimler Truck Retail Polska sp. z o.o., Warszawa","0,00","0,00","0,00","0,00","130,00"
"Dekpol Construction sp. z o.o., Pinczyn","0,00","0,00","152,00","211,00","225,00"
"EPAM Systems (Poland) sp. z o.o., Warszawa",NaN,NaN,"2 616,00","4 771,00","6 174,00"
"EXG Capital sp. z o.o. sp.k., Częstochowa",NaN,NaN,NaN,"28,00","32,00"
"EY Polska, Warszawa",NaN,"2 705,00","3 258,00","3 708,00","3 819,00"
"Elektrix SA, Warszaw",NaN,NaN,NaN,NaN,NaN
"Elektrobudowa sp. z o.o., Warszawa","0,00","0,00","0,00","625,00","784,00"
"Energo Operator sp. z o.o., Warszawa",NaN,NaN,NaN,NaN,NaN
"Enteneo Energy Trading sp. z o.o., Warszawa","0,00","0,00","0,00","0,00","2,00"
"Eupoltrans sp. z o.o., Sady","0,00","48,00","242,00","1 478,00","1 736,00"
"Exclusive Networks Poland SA, Kraków","0,00","22,00","260,00","247,00","243,00"
"Farm Hejła sp. z o.o., Skarszewy",NaN,NaN,NaN,"45,00","47,00"
"Firma Kojs, Jabłonka",NaN,NaN,NaN,NaN,NaN
"Fortis Logistics Group sp. z o.o., Sławków",NaN,NaN,NaN,"58,00","58,00"
"Fortum Silesia SA, Zabrze","0,00","0,00","0,00","0,00","0,00"
"G.En. Gaz Energia sp. z o.o., Warszawa","0,00","0,00","0,00","0,00","38,00"
"Garmin Wrocław sp. z o.o., Biskupice Podgórne","0,00","21,00","49,00","91,00","195,00"
"Gemini Apps sp. z o.o., Gdańsk","0,00","1,00","6,00","5,00","45,00"
"Girpoltrans sp. z o.o., Komorniki","0,00","1 286,00","2 088,00","2 690,00","2 473,00"
"Grant A. Weremczuk sp.k., Kunice","0,00","0,00","0,00",NaN,NaN
"Grupa Cichy Zasada sp. z o.o. sp.j., Wysogotowo","0,00","1 373,00","1 444,00","1 482,00","1 590,00"
"Grupa FAKRO, Nowy Sącz",NaN,NaN,NaN,NaN,NaN
"Grupa Producentów Drobiu sp. z o.o., Bolesławiec",NaN,NaN,NaN,NaN,"70,00"
"HUAWEI Polska sp. z o.o., Warszawa",NaN,NaN,NaN,"216,00","211,00"
"Halfprice sp. z o.o., Polkowice","0,00","0,00","370,00","1 508,00","2 357,00"
"Hanseatic Production sp. z o.o., Grudziądz","0,00","158,00","161,00","185,00","202,00"
"Harden Construction Poland sp. z o.o., Warszawa","0,00","0,00","31,00","51,00","54,00"
"Hekla Energy sp. z o.o., Warszawa","0,00","0,00","5,00","8,00","8,00"
"Hyperoil sp. z o.o., Piaseczno","0,00","0,00","171,00","190,00","157,00"
"INEA sp. z o.o., Przeźmierowo","0,00","0,00","64,00","191,00","204,00"
"INPOST sp. z o.o., Kraków","0,00","1 642,00","2 349,00","2 480,00","2 658,00"
"Infosys Poland sp. z o.o., Łódź","0,00","0,00","0,00","2 902,00","2 876,00"
"Inpost Paczkomaty sp. z o.o., Kraków","0,00","0,00","0,00","0,00","0,00"
"JM Nieruchomości sp. z o.o., Kostrzyn","0,00","0,00","0,00","0,00","0,00"
"Jarosław Dowhan sp.k., Jasień","0,00","0,00","0,00","5,00","5,00"
"Jurassic Crystal sp. z o.o., Zawiercie","0,00","0,00","0,00","0,00","0,00"
"KION Polska sp. z o.o., Kołbaskowo","0,00","0,00","163,00","214,00","236,00"
"Kantor Wymiany Walut sp.j., Gorzów Wlkp.",NaN,NaN,NaN,NaN,NaN
"Koliber Energy Trading sp. z o.o., Warszawa","0,00","0,00","0,00","5,00","5,00"
"Koral Trade sp. z o.o., Nowy Sącz","0,00","0,00","0,00","148,00","136,00"
"Kramel Partner sp. z o.o. sp.k., Piotrków Trybunalski","0,00","0,00","124,00","127,00","130,00"
"LSC Communications sp. z o.o., Warszawa","0,00","0,00","0,00","0,00","0,00"
"Leroy Merlin Inwestycje sp. z o.o., Warszawa",NaN,NaN,NaN,NaN,NaN
"MOS Consulting sp. z o.o., Warszawa","0,00","0,00","0,00","2,00","4,00"
"MSD Polska Dystrybucja sp. z o.o., Warszawa","0,00","0,00","0,00","0,00","0,00"
"Makrochem SA sp.j., Lublin","0,00","0,00","0,00","0,00","0,00"
"Marketing Investment Group SA, Kraków","1 700,00",NaN,NaN,NaN,NaN
"Mazda Motor Poland sp. z o.o., Warszawa","0,00","33,00","33,00","33,00","33,00"
"Menlo Electric SA, Warszawa","0,00","4,00","4,50","12,50","20,00"
"Milkpol Polska sp. z o.o., Warszawa","0,00","0,00","0,00","11,00","10,00"
"Miropasz sp.z o.o., Grójec",NaN,"223,00","223,00","258,00","250,00"
"Mitsubishi Electric Europe B.V. sp. z o.o. w Polsce, Balice",NaN,"239,00","290,00","296,00","342,00"
"Mondry sp. z o.o., Gdańsk","0,00","0,00","0,00","56,00","60,00"
"Müller Dairy Polska sp. z o.o., Poznań","0,00","0,00","0,00","0,00","0,00"
"NOHO Warszawa sp. z o.o., Warszawa","0,00","0,00","0,00","0,00","0,00"
"Naturagra Drób Szlachetny sp. z o.o., Tomaszów Mazowiecki","0,00","0,00","0,00","51,00","60,00"
"OZE Energy sp. z o.o., Warszawa","0,00","0,00","0,00","0,00","0,00"
"Okręgowa Spółdzielnia Mleczarska, Krasnystaw",NaN,"607,00","595,00","556,00","540,00"
"Opella Healthcare Poland sp. z o.o., Warszawa","0,00","0,00","0,00","322,00","384,00"
"P4 Sp. z o.o. GK, Warszawa",NaN,NaN,"2 600,00","2 672,00",NaN
"PG Silesia sp. z o.o., Czechowice-Dziedzice","1 560,00","1 602,00","1 430,00","1 355,00",NaN
"PHU Topaz sp. z o.o., Sokołów Podlaski","0,00",NaN,"2 254,00","2 302,00","2 173,00"
"PHUP Merkury sp.j., Kraków",NaN,NaN,NaN,NaN,NaN
"PLWD sp. z o.o., Świecie","0,00","23,00","28,00","28,00","30,00"
"Panattoni Poland sp. z o.o., Warszawa","0,00","0,00","0,00","0,00","0,00"
"Pol Power sp. z o.o., Komorniki","0,00","0,00","1,00","1,00","6,80"
"Polonia BEEF sp. z o.o., Poznań","0,00","0,00","0,00","5,00","5,00"
"Polska Grupa Fotowoltaiczna SA, Warszawa","0,00","0,00","1,00","190,00","182,00"
"Polski Holding Nieruchomości SA GK, Warszawa","182,97","698,00","698,00",NaN,NaN
"Polski Tytoń SA, Radom","0,00","335,00","321,00","321,00","309,00"
"Polski Światłowód Otwarty sp. z o.o., Warszawa","0,00","0,00","0,00","0,00",NaN
"Polskie Radio SA, Warszawa",NaN,"1 252,00","1 227,00","1 226,00","1 151,00"
"Pozkrone sp.c., Poznań",NaN,NaN,NaN,NaN,NaN
"Premium Arena JTB sp. z o.o. sp.k., Łódź","101,00","106,00","132,00","165,00",NaN
"Pricewaterhousecoopers Polska sp. z o.o. sp.k., Warszawa","0,00","0,00","574,00","606,00","715,00"
"RB (Hygiene Home) Poland sp. z o.o., Nowy Dwór Mazowiecki","0,00","186,00","198,00","204,00","1 787,00"
"REO-PL sp. z o.o., Warszawa","0,00","0,00","0,00","7,00","8,00"
"Rainbow Tours SA GK, Łódź",NaN,NaN,NaN,NaN,NaN
"Rhenus Freight Logistics sp. z o.o., Warszawa","0,00","0,00","0,00","415,00","394,00"
"SDM Manufaktura sp. z o.o., Konstancin-Jeziorna","0,00","1,00","2,00","2,00","3,00"
"STS Holding SA GK, Katowice","0,00","1 293,00","1 258,00","1 201,00","1 100,00"
"Siemens Energy sp. z o.o., Warszawa","0,00","190,00","192,00","230,00","236,00"
"Sikora -AC sp. z o.o., Mikołów",NaN,NaN,NaN,NaN,NaN
"Sk Hi Tech Battery Materials Poland sp. z o.o., Dąbrowa Górnicza","0,00","0,00","414,00","460,00","486,00"
"Smulders Projects Poland sp. z o.o., Żary",NaN,NaN,NaN,"254,00","379,00"
"Solartech sp. z o.o., Warszawa",NaN,NaN,NaN,"21,00","29,00"
"Spectris Energy sp. z o.o., Wraszawa","0,00","6,00","19,00","38,00","42,00"
"Strus Development sp. z o.o., Warszawa","0,00","0,00","45,00","44,00","40,00"
"TADMAR sp. z o.o., Poznań","0,00","0,00","450,00","460,00","457,00"
"Tasomix Pasze sp. z o.o., Nowe Skalmierzyce","0,00","58,00","58,00","67,00","69,00"
"Transeu Poland sp. z o.o., Sady","0,00","0,00","270,00","1 744,00","1 247,00"
"Trend Energy Solutions SA, Warszawa","0,00","0,00","11,00","11,00","12,00"
"Tuplex TD sp. z o.o., Warszawa","0,00","0,00","182,00","182,00","189,00"
"Versuni Poland sp. z o.o., Warszawa","0,00","0,00","170,00","163,00","166,00"
"Waluty Świata sp. z o.o., Słubice","0,00","0,00","0,00","25,00","50,00"
"Warsaw Aviation sp. z o.o., Warszawa","0,00","0,00","0,00","0,00","0,00"
"Warsaw Gas Trading sp. z o.o., Warszawa","0,00","0,00","0,00","0,00","0,00"
"Warsaw Trading Partners sp. z o.o., Warszawa","0,00","0,00","0,00","0,00",NaN
"Wielkopolski Indyk sp. z o.o., Mosina",NaN,NaN,NaN,NaN,NaN
"Wirtualna Polska Media SA, Warszawa",NaN,NaN,NaN,NaN,NaN
"Woodeco Wieruszów sp. z o.o., Wieruszów",NaN,NaN,NaN,NaN,NaN
"Woodeco sp. z o.o., Wrocław",NaN,NaN,NaN,NaN,NaN

In [9]:
#CHECK OF FILTERING

# Select the columns you want to include in the groupby and describe operations
selected_columns = ['Sales', 'Employment']

# Group by Year' and apply describe to the selected columns only
df_summary = df.groupby(['Year'], observed=False)[selected_columns].describe().transpose()
df_filter_summary = df_filter.groupby(['Year'], observed=False)[selected_columns].describe().transpose()
display(df_summary, df_filter_summary)

# Show max and min company
selected_columns = ['Name','Sales', 'Employment']
display(df_filter['Name'].nunique())
display(df_filter.loc[df_filter['Sales'].idxmax(),selected_columns])
display(df_filter.loc[df_filter[df_filter['Year'] == 2023]['Sales'].idxmin(),selected_columns])

display(df_filter[selected_columns].head())

display(df_filter[selected_columns].tail())

Year                       2019          2020           2021           2022  \
Sales      count       1 997,00      1 998,00       1 999,00       1 998,00
           mean    1 168 054,12  1 179 978,68   1 445 060,03   1 916 175,32
           std     3 515 013,85  3 279 087,17   4 274 558,40   7 499 999,48
           min             0,00          0,00           0,00           0,00
           25%       321 337,00    328 957,55     402 227,18     516 109,70
           50%       499 357,00    507 129,28     620 447,58     779 418,17
           75%       943 506,00    944 050,46   1 138 381,04   1 406 117,98
           max   111 203 000,00 86 180 000,00 131 341 000,00 282 415 000,00
Employment count       1 970,00      1 968,00       1 975,00       1 982,00
           mean        1 312,09      1 345,75       1 376,42       1 411,58
           std         3 839,51      4 006,84       4 019,99       4 183,20
           min             0,00          0,00           0,00           0,00
           25%           161,25        167,75         183,00         200,00
           50%           449,00        461,00         480,00         498,00
           75%         1 065,50      1 100,75       1 117,50       1 147,00
           max        80 116,00     78 873,00      74 350,50      77 726,70

Year                       2023
Sales      count       2 000,00
           mean    2 055 787,13
           std     9 539 660,79
           min       403 245,00
           25%       534 699,75
           50%       788 226,00
           75%     1 458 675,41
           max   372 767 000,00
Employment count       1 978,00
           mean        1 433,55
           std         4 254,91
           min             0,00
           25%           206,00
           50%           505,50
           75%         1 182,00
           max        79 292,00

Year                       2019          2020           2021           2022  \
Sales      count       1 887,00      1 887,00       1 886,00       1 885,00
           mean    1 217 583,30  1 227 033,44   1 497 740,07   1 974 685,13
           std     3 603 185,78  3 358 752,27   4 388 039,18   7 711 929,57
           min           166,51      1 395,58       7 380,00      57 305,00
           25%       337 312,32    348 828,99     417 693,40     524 766,00
           50%       516 642,00    527 183,55     642 186,17     799 607,00
           75%       976 216,00    973 195,55   1 166 199,50   1 428 889,24
           max   111 203 000,00 86 180 000,00 131 341 000,00 282 415 000,00
Employment count       1 887,00      1 881,00       1 885,00       1 887,00
           mean        1 367,92      1 400,25       1 423,03       1 456,35
           std         3 913,28      4 089,10       4 102,89       4 274,70
           min             1,00          1,00           1,00           1,00
           25%           194,50        202,00         210,00         221,50
           50%           479,00        489,00         500,00         517,00
           75%         1 102,00      1 132,00       1 149,00       1 163,50
           max        80 116,00     78 873,00      74 350,50      77 726,70

Year                       2023
Sales      count       1 887,00
           mean    2 107 393,56
           std     9 804 957,34
           min       403 245,00
           25%       539 645,42
           50%       800 161,00
           75%     1 482 951,64
           max   372 767 000,00
Employment count       1 887,00
           mean        1 475,95
           std         4 343,21
           min             1,00
           25%           224,00
           50%           525,00
           75%         1 194,50
           max        79 292,00

1887

Name          Orlen SA GK, Płock
Sales             372 767 000,00
Employment             66 554,00
Name: 0, dtype: object

Name          Yes Biżuteria SA GK, Poznań
Sales                          403 245,00
Employment                         266,00
Name: 1999, dtype: object

                                           Name          Sales  Employment
0                            Orlen SA GK, Płock 372 767 000,00   66 554,00
1          Jeronimo Martins Polska SA, Kostrzyn  98 022 928,00   79 292,00
2   PGE Polska Grupa Energetyczna GK SA, Lublin  95 964 000,00   42 552,00
3  Totalizator Sportowy sp. z o.o. GK, Warszawa  52 269 058,00    5 894,00
4                            Enea SA GK, Poznań  48 183 419,00   17 853,00

                                             Name      Sales  Employment
9994                    Rola sp. z o.o., Człuchów 186 787,46       42,00
9995                 Qemetica Silicates SA, Iłowa 237 477,58      322,00
9997                       TZF Polfa SA, Warszawa 250 218,63    1 082,00
9998  Angelini Pharma Polska sp. z o.o., Warszawa 241 910,51      218,00
9999                  Yes Biżuteria SA GK, Poznań 310 627,45      274,00

In [10]:
#ADDING DESCRIPTIVE ANALYSIS DIMENSIONS

# Create a copy of df_filter to avoid the SettingWithCopyWarning
df_filter = df_filter.copy()

#Export as % of Sales
df_filter['Export as % of Sales']= df_filter['Export Sales'] / df_filter['Sales'] *100

#ROA / ROS / ROE
df_filter['ROS']= df_filter['Net Profit'] / df_filter['Sales']
df_filter['ROA']= df_filter['Net Profit'] / df_filter['BS']  
df_filter['ROE']= df_filter['Net Profit'] / df_filter['Equity']

# Polish / Foreign Companies
df_filter['P/F'] = np.where((df_filter['Owner Type'].astype(str).str[:1] == '5'), 'F', 'P')
df_filter['P/F'] = df_filter['P/F'].astype('category')

# BalanceSheet Strength - Equity / BS
df_filter['BS'] = df_filter['BS'].replace(0, np.nan) # Replace 0 in the BS column with NaN to avoid division by zero
df_filter['BS_Strength'] = df_filter['Equity'] / df_filter['BS']

# Human Capital Proxy - Staff costs / employment
df_filter['Human_Capital'] = df_filter['Staff costs'] / df_filter['Employment']

# GVA (Gross Profit + Staff Costs)
df_filter['GVA']=df_filter['Gross Profit'] + df_filter['Staff costs']

# Productivity
df_filter['Productivity']=df_filter['GVA'] / df_filter['Employment']

In [11]:
#SALES & PROFITABILITY STATISTICS

# Isolate the annual growth rate threshold
inflation = 8.5 # (38,5% inflation between 2019 and 2023 - 3,4%	5,1%	14,4%	11,4%)
stability_threshold = 10 #(97,2% of nominal compound growth between 2019 and 2023)
growth_threshold = 20 #(172,8% of nominal compound growth between 2019 and 2023)

# Pivot the DataFrame to make year-based comparison easier for both Sales and Export
#(use only with 2023 set as a filter)
pivot_sales = df_filter.pivot(index='Name', columns='Year', values='Sales')
pivot_export_sales = df_filter.pivot(index='Name', columns='Year', values='Export Sales')
pivot_gva = df_filter.pivot(index='Name', columns='Year', values='GVA')

# High Internationalisation Export Sales > 25% of Sales
pivot_sales['Hint25'] = (pivot_export_sales[2023] / pivot_sales[2023]) > 0.25
pivot_sales['Hint25'] = pivot_sales['Hint25'].apply(lambda x: 'Exp>25' if x else 'Exp<25')

# High Internationalisation Export Sales > 50% of Sales
pivot_sales['Hint50'] = (pivot_export_sales[2023] / pivot_sales[2023]) > 0.50
pivot_sales['Hint50'] = pivot_sales['Hint50'].apply(lambda x: 'Exp>50' if x else 'Exp<50')

# HGX Export Driven
pivot_sales['HGX'] = (pivot_export_sales[2023] / pivot_sales[2023]) > (pivot_export_sales[2019] / pivot_sales[2019])
pivot_sales['HGX'] = pivot_sales['HGX'].apply(lambda x: 'Increased Export Intensity' if x else 'Decreased Export Intensity')

# HGX Export Driven
pivot_sales['HGX%'] = pivot_export_sales[2023] / pivot_sales[2023] - pivot_export_sales[2019] / pivot_sales[2019]


# Sales Growth_2023_2019 (Total and Annualised Growth)
pivot_sales['SGrowth_2023_2019'] = (pivot_sales[2023] - pivot_sales[2019]) / pivot_sales[2019] * 100
pivot_sales['Annualised_Growth'] = ((pivot_sales[2023] / pivot_sales[2019]) ** (1/4) - 1) * 100
# Sales Growth 2023_2019 - ln transformation
pivot_sales['LSGrowth_2023_2019'] = np.log(pivot_sales[2023]) - np.log(pivot_sales[2019])

pivot_sales['RealSales_2023'] = pivot_sales[2023] / 1.38
pivot_sales['RSGrowth_2023_2019'] = ((pivot_sales[2023] / 1.38) - pivot_sales[2019]) / pivot_sales[2019] * 100
pivot_sales['LRSGrowth_2023_2019'] = np.log(pivot_sales['RealSales_2023']) - np.log(pivot_sales[2019])

# Sales Drop Conditions

pivot_sales['Drop_Sales_2020'] = (pivot_sales[2020]/(1+0.034) < pivot_sales[2019])
pivot_sales['Drop_Sales_2020'] = pivot_sales['Drop_Sales_2020'].apply(lambda x: 'Yes' if x else 'No')

pivot_sales['Drop_Sales_2023'] = (pivot_sales[2023]/(1+0.114) < pivot_sales[2022])
pivot_sales['Drop_Sales_2023'] = pivot_sales['Drop_Sales_2023'].apply(lambda x: 'Yes' if x else 'No')

pivot_sales['Drop_Sales_Both'] = (pivot_sales[2023]/(1+0.114) < pivot_sales[2022]) & (pivot_sales[2020]/(1+0.034) < pivot_sales[2019])
pivot_sales['Drop_Sales_Both'] = pivot_sales['Drop_Sales_Both'].apply(lambda x: 'Yes' if x else 'No')


# GVA Growth_2023_2019 (in PLN)
pivot_gva['GVAGrowth_2023_2019'] = (pivot_gva[2023] - pivot_gva[2019])


# Add Growth column with 3 growth categories
def categorize_growth(row):
    if row['Annualised_Growth'] > (growth_threshold + inflation):
        return '3.Very High'
    elif (stability_threshold + inflation) < row['Annualised_Growth'] <= (growth_threshold + inflation):
        return '2.High'
    elif inflation < row['Annualised_Growth'] <= (stability_threshold + inflation):
        return '1.Moderate'
    else:
        return '0.Below Inflation'

pivot_sales['SGrowth_3'] = pivot_sales.apply(categorize_growth, axis=1)

# Add # Add Growth column with 2 growth categories
def categorize_growth1(row):
    if row['Annualised_Growth'] > (growth_threshold):
        return '3.High Growth'
    elif inflation <= row['Annualised_Growth'] <= (growth_threshold):
        return '2.Stable'
    elif 0 < row['Annualised_Growth'] <= inflation:
        return '1.Declining'
    else:
        return '0.Stressed'             

pivot_sales['SGrowth_2'] = pivot_sales.apply(categorize_growth1, axis=1)

# Add # Add Growth column with 1 growth category
def categorize_growth2(row):
    if row['Annualised_Growth'] > (inflation):
        return 'Growing'
    else:
        return 'Declining'
pivot_sales['SGrowth_1'] = pivot_sales.apply(categorize_growth2, axis=1)

# Merge the calculated columns back to the original df_filter DataFrame
df_filter = df_filter.merge(pivot_sales[['Hint25','Hint50','HGX','HGX%','SGrowth_2023_2019','LSGrowth_2023_2019','RSGrowth_2023_2019','LRSGrowth_2023_2019','Annualised_Growth', 'Drop_Sales_2020', 'Drop_Sales_2023','Drop_Sales_Both','SGrowth_3','SGrowth_2','SGrowth_1']], on='Name')
df_filter = df_filter.merge(pivot_gva['GVAGrowth_2023_2019'], on='Name')

In [12]:
#EMPLOYMENT STATISTICS

# Pivot the DataFrame to make year-based comparison easier for Employment
#(use only with 2023 set as a filter)
pivot_employment = df_filter.pivot(index='Name', columns='Year', values='Employment')
pivot_productivity = df_filter.pivot(index='Name',columns='Year',values='Productivity')

# Calculate Employment Growth_2023_2019 (Total Growth)
pivot_employment['EGrowth_2023_2019'] = (pivot_employment[2023] - pivot_employment[2019]) / pivot_employment[2019] * 100
# Employment Growth (Percentage) - ln transformation
pivot_employment['LEGrowth_2023_2019'] = np.log(pivot_employment[2023]) - np.log(pivot_employment[2019])

pivot_employment['Annualised_EGrowth'] = ((pivot_employment[2023] / pivot_employment[2019]) ** (1/4) - 1) * 100

# Calculate Productivity Growth_2023_2019 (Total Growth)
pivot_productivity['PGrowth_2023_2019'] = pivot_productivity[2023] - pivot_productivity[2019]


# Add Growth column with 3 categories
def categorize_egrowth(row):
    if row['EGrowth_2023_2019'] < 0:
        return '0.Reducing'
    elif (0) < row['Annualised_EGrowth'] <= (1.10):
        return '1.Sustaining'
    else:
        return '2.Hiring'

pivot_employment['EGrowth_3'] = pivot_employment.apply(categorize_egrowth, axis=1)

# Add Growth column with 2 categories
def categorize_egrowth1(row):
    if row['EGrowth_2023_2019'] < 0:
        return 'Reducing'
    else:
        return 'Hiring'

pivot_employment['EGrowth_2'] = pivot_employment.apply(categorize_egrowth1, axis=1)
    
# Calculate Employment Drop conditions
#pivot_employment['Drop_Employment'] = (pivot_employment[2020] < pivot_employment[2019]) | (pivot_employment[2021] < pivot_employment[2020]) | (pivot_employment[2022] < pivot_employment[2021]) | (pivot_employment[2023] < pivot_employment[2022])
pivot_employment['Drop_Employment'] = (pivot_employment[2020] < pivot_employment[2019])
pivot_employment['Drop_Employment'] = pivot_employment['Drop_Employment'].apply(lambda x: 'Yes' if x else 'No')

# Step 5: Merge the calculated columns back to the original df_filter DataFrame
df_filter = df_filter.merge(pivot_employment[['EGrowth_2023_2019','LEGrowth_2023_2019','Annualised_EGrowth','Drop_Employment','EGrowth_3','EGrowth_2']], on='Name')
df_filter = df_filter.merge(pivot_productivity['PGrowth_2023_2019'], on='Name')

In [13]:
#ADDING ADDITIONAL REGRESSION ANALYSIS DIMENSIONS

#np.arcsinh() used for all variables because it handles negative 
#zero, and positive values consistently, compresses outliers effectively,
#and ensures robustness across your regression analysis.
#arcsinh(x)=ln(x+ squared root(x^2+1))


# Starting Profit - ROS in 2019
ros_2019 = df_filter[df_filter['Year'] == 2019].set_index('Name')['ROS'] # Step 1: Extract 2019 ROS values
df_filter['Starting_Profit'] = df_filter['Name'].map(ros_2019)# Step 2: Map 2019 ROS values to the 'Starting_Profit' column for all rows

# Starting Internationalisation level - #Export as % of Sales in 2019
Starting_INT = df_filter[df_filter['Year'] == 2019].set_index('Name')['Export as % of Sales'] # Step 1: Extract 2019 Export as % of Sales values
df_filter['Starting_INT'] = df_filter['Name'].map(Starting_INT)# Step 2: Map 2019 Export as % values to the 'Starting_INT' column for all rows

#Starting BS Strength
bs_2019 = df_filter[df_filter['Year'] == 2019].set_index('Name')['BS_Strength'] # Step 1: Extract 2019 BS_Strength values
df_filter['Starting_BS_Strength'] = df_filter['Name'].map(bs_2019)# Step 2: Map 2019 ROS values to the 'Starting_Profit' column for all rows

# Starting Size - natural log of Sales for 2019
ln_sales_2019 = df_filter[df_filter['Year'] == 2019].set_index('Name')['Sales'].apply(np.log)
df_filter['Starting_Size_ln'] = df_filter['Name'].map(ln_sales_2019)  # Step 2: Map these values to the 'Starting_Size' column

#Starting HC Strength
hc_2019 = df_filter[df_filter['Year'] == 2019].set_index('Name')['Human_Capital']
df_filter['Starting_Human_Capital']=df_filter['Name'].map(hc_2019)

# Starting GVA - GVA in 2019
gva_2019 = df_filter[df_filter['Year'] == 2019].set_index('Name')['GVA'] # Step 1: Extract 2019 GVA values
df_filter['Starting_GVA'] = df_filter['Name'].map(gva_2019)# Step 2: Map 2019 GVA values to the 'Starting_GVA' column for all rows

# Starting Productivity - Productivity in 2019
productivity_2019 = df_filter[df_filter['Year'] == 2019].set_index('Name')['Productivity'] # Step 1: Extract 2019 Productivity values
df_filter['Starting_Prod'] = df_filter['Name'].map(productivity_2019)# Step 2: Map 2019 Productivity values to the 'Starting_Prod' column for all rows


#OPTIONAL arcsinh calculations

# Starting Size - arcsinh sales in 2019
#arcsinh_sales_2019 = df_filter[df_filter['Year'] == 2019].set_index('Name')['Sales'].apply(np.arcsinh)  # Step 1: Calculate arcsinh(Sales) for 2019
#f_filter['Starting_Size_arc'] = df_filter['Name'].map(arcsinh_sales_2019)  # Step 2: Map these values to the 'Starting_Size' column


# Sales Growth (Percentage) - arcsinh transformation
#df_filter['ASGrowth_2023_2019'] = np.arcsinh(df_filter['SGrowth_2023_2019'] / 100)

# Real Sales Growth (Percentage) - arcsinh transformation
#df_filter['ARSGrowth_2023_2019'] = np.arcsinh(df_filter['RSGrowth_2023_2019'] / 100)

# Employment Growth (Percentage) - arcsinh transformation
#df_filter['AEGrowth_2023_2019'] = np.arcsinh(df_filter['EGrowth_2023_2019'] / 100)

# GVA Growth (Nominal PLN) - arcsinh transformation
#df_filter['AGVAGrowth_2023_2019'] = np.arcsinh(df_filter['GVAGrowth_2023_2019'])

# Productivity Growth (Nominal PLN) - arcsinh transformation
#df_filter['APGrowth_2023_2019'] = np.arcsinh(df_filter['PGrowth_2023_2019'])

In [28]:
# Filter for year 2023 and get top 10 by sales growth
top_10_growth_2023 = df_filter[df_filter['Year'] == 2023][['Name', 'SGrowth_2023_2019']]\
    .sort_values(by='SGrowth_2023_2019', ascending=False).head(10)

# Correct: Sort ascending to get bottom 10
bottom_10_growth_2023 = df_filter[df_filter['Year'] == 2023][['Name', 'SGrowth_2023_2019']]\
    .sort_values(by='SGrowth_2023_2019', ascending=True).head(10)

display(top_10_growth_2023)

display(bottom_10_growth_2023)


# DATA WITH COMMENTS
df_filter.to_excel('2000 Analysis Python CALCULATED.xlsx', index=False)

print("DataFrame 'df_filter' has been saved to '2000 Analysis Python CALCULATED.xlsx'.")

                                                Name  SGrowth_2023_2019
399              Ignitis Polska sp. z o.o., Warszawa          35 355,01
59                  Axpo Polska sp. z o.o., Warszawa           2 728,86
21     Grupa Kapitałowa Specjał sp. z o.o., Warszawa             961,00
51                         Eniq sp. z o.o., Katowice             645,85
110               Bunge Polska sp. z o.o., Kruszwica             625,95
190         ZF CV Systems Poland sp. z o.o., Wrocław             550,82
374  Viessmann Technika Grzewcza sp. z o.o., Legnica             500,15
363                      Enefit sp. z o.o., Warszawa             447,03
382    Flextronics Logistics Poland sp. z o.o., Łódź             445,53
3       Totalizator Sportowy sp. z o.o. GK, Warszawa             428,35

                                          Name  SGrowth_2023_2019
79               MOL Polska sp. z o.o., Gdańsk             -72,33
136         Netto Indygo sp. z o.o., Kobylanka             -58,21
1628          Olam Polska sp. z o.o., Warszawa             -57,97
1102              Control Process SA, Warszawa             -49,23
1589  DXC Technology Polska sp. z.o., Warszawa             -45,47
836         Grupa Nowy Styl sp. z o.o., Krosno             -45,38
1524  Coty Eastern Europe sp. z o.o., Warszawa             -45,11
592                       Skanska SA, Warszawa             -41,61
1054       Casinos Poland sp. z o.o., Warszawa             -40,83
1287              OT Logistics SA GK, Szczecin             -39,87

DataFrame 'df_filter' has been saved to '2000 Analysis Python CALCULATED.xlsx'.

In [15]:
# SET THE ANALYTICAL FILTERS

# Identify names with outlier Export as % of Sales
names_to_remove = df_filter[
    (df_filter['Year'].isin([2019, 2023])) & 
    (df_filter['Export as % of Sales'] > 100)
]['Name'].unique()

# Remove those companies + those not present in 2019 list
df_filter = df_filter[
    df_filter['2019'].notna() & (~df_filter['Name'].isin(names_to_remove))
]

# Optional filter: remove fuel sector companies (PKD_2 == '19')
# Uncomment next line to activate
# company_filter = df_filter[df_filter['PKD_2'] == '19']

if 'company_filter' in locals():
    df_filter = df_filter[~df_filter.index.isin(company_filter.index)]
    num_sector_removed = company_filter['Name'].nunique()
else:
    num_sector_removed = 0

# Show results
print(f"Number of companies removed due to sector considerations: {num_sector_removed}")
print(f"Number of companies removed due to Export as % of Sales > 100 in 2019 or 2023: {len(names_to_remove)}")

count_df = df[
    (df['2023'] != 0) & (df['2023'].notna()) & 
    (df['2019'] != 0) & (df['2019'].notna()) & 
    (df['Year'] == 2023)
].shape[0]
print("Number of companies from 2019 list before filtering = ", count_df)

count_df_filter = df_filter[df_filter['Year'] == 2023].shape[0]
print("Number of companies from 2019 list after filtering = ", count_df_filter)

Number of companies removed due to sector considerations: 0
Number of companies removed due to Export as % of Sales > 100 in 2019 or 2023: 25
Number of companies from 2019 list before filtering =  1535
Number of companies from 2019 list after filtering =  1490

In [16]:
#CHECK OF FILTERING

# Select the columns you want to include in the groupby and describe operations
selected_columns = ['Sales']

# Group by Year' and apply describe to the selected columns only
df_summary = df.groupby(['Year'], observed=False)[selected_columns].describe().transpose()
df_filter_summary = df_filter.groupby(['Year'], observed=False)[selected_columns].describe().transpose()
display(df_summary, df_filter_summary)

# Show max and min company
selected_columns = ['Name','Sales', 'Employment']
display(df_filter['Name'].nunique())
display(df_filter.loc[df_filter['Sales'].idxmax(),selected_columns])
display(df_filter.loc[df_filter[df_filter['Year'] == 2023]['Sales'].idxmin(),selected_columns])

display(df_filter[selected_columns].head())

display(df_filter[selected_columns].tail())

Year                  2019          2020           2021           2022  \
Sales count       1 997,00      1 998,00       1 999,00       1 998,00
      mean    1 168 054,12  1 179 978,68   1 445 060,03   1 916 175,32
      std     3 515 013,85  3 279 087,17   4 274 558,40   7 499 999,48
      min             0,00          0,00           0,00           0,00
      25%       321 337,00    328 957,55     402 227,18     516 109,70
      50%       499 357,00    507 129,28     620 447,58     779 418,17
      75%       943 506,00    944 050,46   1 138 381,04   1 406 117,98
      max   111 203 000,00 86 180 000,00 131 341 000,00 282 415 000,00

Year                  2023
Sales count       2 000,00
      mean    2 055 787,13
      std     9 539 660,79
      min       403 245,00
      25%       534 699,75
      50%       788 226,00
      75%     1 458 675,41
      max   372 767 000,00

Year                  2019          2020           2021           2022  \
Sales count       1 490,00      1 490,00       1 489,00       1 488,00
      mean    1 441 703,22  1 436 984,93   1 748 274,19   2 292 939,92
      std     4 007 894,56  3 731 301,38   4 886 012,31   8 627 365,85
      min         4 743,00     14 316,00       7 380,00      65 528,83
      25%       418 085,52    421 141,47     501 414,00     612 250,51
      50%       620 407,23    622 538,08     761 966,00     926 190,11
      75%     1 157 778,50  1 123 902,38   1 348 360,00   1 671 292,96
      max   111 203 000,00 86 180 000,00 131 341 000,00 282 415 000,00

Year                  2023
Sales count       1 490,00
      mean    2 435 180,75
      std    10 987 343,23
      min       403 245,00
      25%       609 600,53
      50%       941 577,19
      75%     1 677 552,04
      max   372 767 000,00

1490

Name          Orlen SA GK, Płock
Sales             372 767 000,00
Employment             66 554,00
Name: 0, dtype: object

Name          Yes Biżuteria SA GK, Poznań
Sales                          403 245,00
Employment                         266,00
Name: 1886, dtype: object

                                           Name          Sales  Employment
0                            Orlen SA GK, Płock 372 767 000,00   66 554,00
1          Jeronimo Martins Polska SA, Kostrzyn  98 022 928,00   79 292,00
2   PGE Polska Grupa Energetyczna GK SA, Lublin  95 964 000,00   42 552,00
3  Totalizator Sportowy sp. z o.o. GK, Warszawa  52 269 058,00    5 894,00
4                            Enea SA GK, Poznań  48 183 419,00   17 853,00

                                                 Name      Sales  Employment
9420               Dom Volvo Car sp. z o.o., Warszawa 322 902,00       92,00
9424      Piast Pasze sp. z o.o., Ostrów Wielkopolski 255 135,28      105,00
9427                      Cortland sp. z o.o., Poznań 332 263,47       64,00
9429  Hodowla i Ubój Indyka Biodama sp. z o.o., Sława 328 825,00      250,00
9434                      Yes Biżuteria SA GK, Poznań 310 627,45      274,00

In [17]:
# CLOSING CODES
df_filter.to_excel('2000 Analysis Python CHANGED.xlsx', index=False)

print("DataFrame 'df_filter' has been saved to '2000 Analysis Python CHANGED.xlsx'.")

DataFrame 'df_filter' has been saved to '2000 Analysis Python CHANGED.xlsx'.

In [18]:
df_summary = df_filter.groupby(['Year'], observed=False)[['Sales','Employment']].describe().transpose()

display(df_summary)

df_summary.to_excel('Results/Summary Stats.xlsx', index=True)

Year                       2019          2020           2021           2022  \
Sales      count       1 490,00      1 490,00       1 489,00       1 488,00
           mean    1 441 703,22  1 436 984,93   1 748 274,19   2 292 939,92
           std     4 007 894,56  3 731 301,38   4 886 012,31   8 627 365,85
           min         4 743,00     14 316,00       7 380,00      65 528,83
           25%       418 085,52    421 141,47     501 414,00     612 250,51
           50%       620 407,23    622 538,08     761 966,00     926 190,11
           75%     1 157 778,50  1 123 902,38   1 348 360,00   1 671 292,96
           max   111 203 000,00 86 180 000,00 131 341 000,00 282 415 000,00
Employment count       1 490,00      1 487,00       1 488,00       1 490,00
           mean        1 588,18      1 618,45       1 638,73       1 667,93
           std         4 286,90      4 484,20       4 504,63       4 698,47
           min             1,00          1,00           1,00           1,00
           25%           249,00        248,00         254,25         269,25
           50%           572,50        570,00         571,00         581,50
           75%         1 345,25      1 374,00       1 383,75       1 374,75
           max        80 116,00     78 873,00      74 350,50      77 726,70

Year                       2023
Sales      count       1 490,00
           mean    2 435 180,75
           std    10 987 343,23
           min       403 245,00
           25%       609 600,53
           50%       941 577,19
           75%     1 677 552,04
           max   372 767 000,00
Employment count       1 490,00
           mean        1 684,39
           std         4 775,35
           min             1,00
           25%           271,00
           50%           589,50
           75%         1 406,00
           max        79 292,00

In [19]:
# Filter for 2023
df_2023 = df_filter[df_filter['Year'] == 2023]

# Choose variables to summarize
columns_of_interest = ['LSGrowth_2023_2019','Starting_INT', 'Starting_BS_Strength','Starting_Size_ln', 'Starting_Profit',
                      'HGX%']  # add more if needed

# Compute and transpose the summary
df_summary_2023 = df_2023[columns_of_interest].describe().transpose()

# Display and export
display(df_summary_2023.T)
df_summary_2023.T.to_excel('Results/Summary Stats 2023.xlsx')

,LSGrowth_2023_2019,Starting_INT,Starting_BS_Strength,Starting_Size_ln,Starting_Profit,HGX%
count,"1 490,00","1 482,00","1 483,00","1 490,00","1 485,00","1 474,00"
mean,"0,40","29,95","0,42","13,57","0,04","-0,01"
std,"0,36","34,27","0,25","0,88","0,08","0,16"
min,"-1,28","0,00","-1,44","8,46","-0,70","-1,00"
25%,"0,20","0,12","0,26","12,94","0,01","-0,02"
50%,"0,37","12,59","0,41","13,34","0,03","0,00"
75%,"0,55","57,58","0,59","13,96","0,06","0,02"
max,"5,87","100,00","0,98","18,53","0,90","1,00"